const bcrypt = require("bcryptjs");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const password = bcrypt.hashSync("123456Abcd!");
const startDateTime = new Date("2024-06-10 18:00:00").toISOString();
const endDateTime = new Date("2024-06-10 24:00:00").toISOString();

const userData = [
  { email: "a@gmail.com", password: password, role: "ADMIN" },
  { email: "b@gmail.com", password: password, role: "CUSTOMER" },
  {
    email: "c@gmail.com",
    password: password,
    googleId: "123456",
    role: "CUSTOMER",
  },
  {
    email: "d@gmail.com",
    password: password,
    googleId: "123456",
    role: "CUSTOMER",
  },
];
// const eventData = [
//   {
//     name: "EVENT1",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistA",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//       ],
//     },
//   },
//   {
//     name: "EVENT2",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistB",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//       ],
//     },
//   },
//   {
//     name: "EVENT3",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistC",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//       ],
//     },
//   },
//   {
//     name: "EVENT4",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistD",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//       ],
//     },
//   },
//   {
//     name: "EVENT5",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistE",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//       ],
//     },
//   },
//   {
//     name: "EVENT6",
//     details: "The biggest concert to celebrate 10 year anniversary of our band",
//     artist: "ArtistF",
//     organizer: "BigRoom",
//     avenue: "Impact Arena, Muang Thong Thani",
//     coverImage: "https://picsum.photos/seed/picsum/400/400",
//     profileImage: "https://picsum.photos/seed/picsum/400/400",
//     seatMapImage: "https://picsum.photos/seed/picsum/400/400",
//     contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
//     startDateTime: startDateTime,
//     endDateTime: endDateTime,
//     ticketTypes: {
//       create: [
//         {
//           name: "ZoneA",
//           details: "VIP Zone. Only 100 seats.",
//           maximumSeat: 100,
//           remainingSeat: 100,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 5000.0,
//         },
//         {
//           name: "ZoneB",
//           details: "Special Zone. 500 seats.",
//           maximumSeat: 500,
//           remainingSeat: 500,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 3000.0,
//         },
//         {
//           name: "ZoneC",
//           details: "For everyone. 1000 seats",
//           maximumSeat: 1000,
//           remainingSeat: 1000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1500.0,
//         },
//         {
//           name: "ZoneD",
//           details: "For everyone. 2000 seats",
//           maximumSeat: 2000,
//           remainingSeat: 2000,
//           ticketImage: "https://picsum.photos/seed/picsum/400/400",
//           price: 1000.0,
//         },
//       ],
//     },
//   },
// ];

const eventData = [
  {
    name: "EVENT1",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistA",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT2",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistB",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT3",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistC",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT4",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistD",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT5",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistA",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT6",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistA",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT7",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistA",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
  {
    name: "EVENT8",
    details: "The biggest concert to celebrate 10 year anniversary of our band",
    artist: "ArtistA",
    organizer: "BigRoom",
    avenue: "Impact Arena, Muang Thong Thani",
    coverImage: "https://picsum.photos/seed/picsum/400/400",
    profileImage: "https://picsum.photos/seed/picsum/400/400",
    seatMapImage: "https://picsum.photos/seed/picsum/400/400",
    contractAddress: "0x118dfa1E8057C16E5E3e50961b5758134ba40367",
    startDateTime: startDateTime,
    endDateTime: endDateTime,
  },
];
const ticketTypeData = [
  {
    eventId: 1,
    name: "ZoneA",
    details: "VIP Zone. Only 100 seats.",
    maximumSeat: 100,
    remainingSeat: 100,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 5000.0,
  },
  {
    eventId: 1,
    name: "ZoneB",
    details: "Special Zone. 500 seats.",
    maximumSeat: 500,
    remainingSeat: 500,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 3000.0,
  },
  {
    eventId: 1,
    name: "ZoneC",
    details: "For everyone. 1000 seats",
    maximumSeat: 1000,
    remainingSeat: 1000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1500.0,
  },
  {
    eventId: 1,
    name: "ZoneD",
    details: "For all. 2000 seats",
    maximumSeat: 2000,
    remainingSeat: 2000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1000.0,
  },
  {
    eventId: 2,
    name: "ZoneAA",
    details: "VIP Zone. Only 100 seats.",
    maximumSeat: 100,
    remainingSeat: 100,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 5000.0,
  },
  {
    eventId: 2,
    name: "ZoneAB",
    details: "Special Zone. 500 seats.",
    maximumSeat: 500,
    remainingSeat: 500,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 3000.0,
  },
  {
    eventId: 2,
    name: "ZoneAC",
    details: "For everyone. 1000 seats",
    maximumSeat: 1000,
    remainingSeat: 1000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1500.0,
  },
  {
    eventId: 2,
    name: "ZoneAD",
    details: "For all. 2000 seats",
    maximumSeat: 2000,
    remainingSeat: 2000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1000.0,
  },
  {
    eventId: 3,
    name: "ZoneA",
    details: "VIP Zone. Only 100 seats.",
    maximumSeat: 100,
    remainingSeat: 100,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 5000.0,
  },
  {
    eventId: 3,
    name: "ZoneB",
    details: "Special Zone. 500 seats.",
    maximumSeat: 500,
    remainingSeat: 500,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 3000.0,
  },
  {
    eventId: 3,
    name: "ZoneC",
    details: "For everyone. 1000 seats",
    maximumSeat: 1000,
    remainingSeat: 1000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1500.0,
  },
  {
    eventId: 4,
    name: "ZoneA",
    details: "VIP Zone. Only 100 seats.",
    maximumSeat: 100,
    remainingSeat: 100,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 5000.0,
  },
  {
    eventId: 4,
    name: "ZoneB",
    details: "Special Zone. 500 seats.",
    maximumSeat: 500,
    remainingSeat: 500,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 3000.0,
  },
  {
    eventId: 5,
    name: "ZoneAA",
    details: "For everyone. 1000 seats",
    maximumSeat: 1000,
    remainingSeat: 1000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1500.0,
  },
  {
    eventId: 5,
    name: "ZoneAB",
    details: "For all. 2000 seats",
    maximumSeat: 2000,
    remainingSeat: 2000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1000.0,
  },
  {
    eventId: 5,
    name: "ZoneA",
    details: "VIP Zone. Only 100 seats.",
    maximumSeat: 100,
    remainingSeat: 100,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 5000.0,
  },
  {
    eventId: 5,
    name: "ZoneB",
    details: "Special Zone. 500 seats.",
    maximumSeat: 500,
    remainingSeat: 500,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 3000.0,
  },
  {
    eventId: 5,
    name: "ZoneC",
    details: "For everyone. 1000 seats",
    maximumSeat: 1000,
    remainingSeat: 1000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1500.0,
  },
  {
    eventId: 5,
    name: "ZoneD",
    details: "For all. 2000 seats",
    maximumSeat: 2000,
    remainingSeat: 2000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1000.0,
  },
  {
    eventId: 6,
    name: "ZoneD",
    details: "For all. 2000 seats",
    maximumSeat: 2000,
    remainingSeat: 2000,
    ticketImage: "https://picsum.photos/seed/picsum/400/400",
    price: 1000.0,
  },
];

const run = async () => {
  // await prisma.user.createMany({ data: userData });
  await prisma.event.createMany({ data: eventData });
  await prisma.tickettype.createMany({ data: ticketTypeData });
};

run();
